apiVersion: v1
kind: Pod
metadata:
  name: flask-app-pod
  labels:
    app: flask-app
spec:
  containers:
  - name: flask-app-container
    image: rajdeep1311/flask-cpu-memory-app:latest  # Replace with your actual image name and version
    ports:
    - containerPort: 5000  # Port on which the Flask app listens
